apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-config
  namespace: final
data:
  S3_BUCKET_NAME: "clo835-background-imgs"
  S3_OBJECT_KEY: "bg.jpg"
  MY_NAME: "Salisha-Pratima-Ajay"
  DBHOST: mysql
