apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp
  namespace: final
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskapp
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
      - name: flask-container
        image: 788814499739.dkr.ecr.us-east-1.amazonaws.com/flask-mysql-ecr:app-v1
        ports:
        - containerPort: 81
        env:
        - name: DBHOST
          valueFrom:
            configMapKeyRef:
              name: flask-config
              key: DBHOST
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: DBUSER
        - name: DBPWD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: DBPWD
        - name: DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: DATABASE
        - name: MY_NAME
          valueFrom:
            configMapKeyRef:
              name: flask-config
              key: MY_NAME
        - name: S3_BUCKET_NAME
          valueFrom:
            configMapKeyRef:
              name: flask-config
              key: S3_BUCKET_NAME
        - name: S3_OBJECT_KEY
          valueFrom:
            configMapKeyRef:
              name: flask-config
              key: S3_OBJECT_KEY
