apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
  namespace: final
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
<<<<<<< HEAD
          image: "788814499739.dkr.ecr.us-east-1.amazonaws.com/flask-mysql-ecr:app-v1"
          ports:
            - containerPort: 81
          envFrom:
            - configMapRef:
                name: background-config
=======
          image: "491245135109.dkr.ecr.us-east-1.amazonaws.com/flask-mysql-ecr:app-v1"
          ports:
            - containerPort: 81
          env:
            # MySQL config as app.py expects:
            - name: DBHOST
              value: "mysql-service.final.svc.cluster.local"
            - name: DBUSER
              value: "root"
            - name: DBPWD
              value: ""
            - name: DATABASE
              value: "employees"
            # S3 config as app.py expects:
            - name: S3_BUCKET_NAME
              value: "pratima-clo835-background"
            - name: S3_OBJECT_KEY
              value: "background.jpg"
            # Display name in the HTML
            - name: MY_NAME
              value: "pratima (1513236)"
>>>>>>> cc31bb1 (updated all the manifests files)
