apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  namespace: final
spec:
<<<<<<< HEAD
  ports:
    - port: 80
=======
  type: NodePort
  ports:
    - port: 80
      targetPort: 81
      nodePort: 30080
      protocol: TCP
>>>>>>> cc31bb1 (updated all the manifests files)
  selector:
    app: flask-app
