apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: final
spec:
  ports:
    - port: 3306
<<<<<<< HEAD
=======
      targetPort: 3306
      protocol: TCP
>>>>>>> cc31bb1 (updated all the manifests files)
  selector:
    app: mysql
