apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: final
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
<<<<<<< HEAD
          image: "788814499739.dkr.ecr.us-east-1.amazonaws.com/flask-mysql-ecr:mysql-v1"
          envFrom:
            - secretRef:
                name: mysql-secret
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-storage
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
=======
          # Use the 'mysql-v1' tag here
          image: "491245135109.dkr.ecr.us-east-1.amazonaws.com/flask-mysql-ecr:mysql-v1"
          env:
          env:
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "true"

          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-storage

      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
>>>>>>> cc31bb1 (updated all the manifests files)
