apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: final
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: "788814499739.dkr.ecr.us-east-1.amazonaws.com/flask-mysql-ecr:mysql-v1"
          envFrom:
            - secretRef:
                name: mysql-secret
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-storage
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
