apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: final
type: Opaque
data:
  DBUSER: cm9vdA==          # base64 for 'root'
  DBPWD: cHc=               # base64 for 'pw'
  DATABASE: ZW1wbG95ZWVz    # base64 for 'employees'
